name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia "main" por el nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          mv module2-solution/* .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
